[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "site-management-tutorial"
authors = [{name = "YT", email = "scarletreflection@gmail.com"}]
dynamic = ["version", "description"]
